#! /usr/bin/env python

SELF_CLOSING = ["area", "base", "br", "col", "command", "embed", "hr", "img", "input", "keygen", "link", "param", "meta", "track", "wbr"]
IDRIS_RESERVED = ["data"]
TAG_TYPE = "List Attribute -> List VNode -> VNode"
VOID_TAG_TYPE = "List Attribute -> VNode"

print("-- This file is automatically generated, please do not edit")

print("module TagList\n")
#print("import HTML")
print("import Attributes\n")
print("import Tag\n")

with open("tags.txt", "r") as tags:
    for tag in tags:
        tag = tag.strip()

        if tag in IDRIS_RESERVED:
            tag_name = tag + "'"
        else:
            tag_name = tag

        if tag in SELF_CLOSING:
            tag_func = "VoidTag"
            tag_type = VOID_TAG_TYPE
        else:
            tag_func = "Tag"
            tag_type = TAG_TYPE

        print("export")
        print(f"{tag_name} : {tag_type}")
        print(f'{tag_name} = {tag_func} "{tag}"\n')
